### ISSUE TITLE
inspect command has error: Uncaught Error: Class 'PHPStan\DependencyInjection\ContainerFactory' 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-upgrader#179]
```txt
Array
(
    [0] => PHP Fatal error:  Uncaught Error: Class 'PHPStan\DependencyInjection\ContainerFactory' not found in /var/www/upgrader/vendor/silverstripe/upgrader/src/Util/PHPStanState.php:64
    [1] => Stack trace:
    [2] => #0 /var/www/upgrader/vendor/silverstripe/upgrader/src/Util/PHPStanState.php(43): SilverStripe\Upgrader\Util\PHPStanState->initContainer()
    [3] => #1 /var/www/upgrader/vendor/silverstripe/upgrader/src/Console/InspectCommand.php(60): SilverStripe\Upgrader\Util\PHPStanState->init()
    [4] => #2 /var/www/upgrader/vendor/symfony/console/Command/Command.php(255): SilverStripe\Upgrader\Console\InspectCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    [5] => #3 /var/www/upgrader/vendor/symfony/console/Application.php(924): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    [6] => #4 /var/www/upgrader/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Silve in /var/www/upgrader/vendor/silverstripe/upgrader/src/Util/PHPStanState.php on line 64
)
```

**Comment by sunnysideup** [comment]
```txt

bramus/ansi-php                           3.0.2              ANSI Control Functions and ANSI Control Sequences (Colors, Erasing, etc.) for PHP CLI Apps
bramus/monolog-colored-line-formatter     2.0.3              Colored Line Formatter for Monolog
composer/ca-bundle                        dev-master 3a41bed Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/installers                       v1.6.0             A multi-framework Composer library installer
composer/semver                           dev-master 37e4db2 Semver library that offers utilities, version constraint parsing and validation.
composer/xdebug-handler                   1.3.3              Restarts a process without xdebug.
doctrine/annotations                      1.7.x-dev 3f35255  Docblock Annotations Parser
doctrine/lexer                            1.0.x-dev 1febd6c  PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
embed/embed                               v3.4.0             PHP library to retrieve page info using oembed, opengraph, etc
friendsofphp/php-cs-fixer                 dev-master 06df242 A tool to automatically fix PHP code style
guzzlehttp/guzzle                         dev-master ca2892a Guzzle is a PHP HTTP client library
guzzlehttp/promises                       dev-master 17d36ed Guzzle promises library
guzzlehttp/psr7                           1.x-dev 239400d    PSR-7 message implementation that also provides common utility methods
intervention/image                        2.5.0              Image handling and manipulation library with support for Laravel integration
jean85/pretty-package-versions            dev-master d6d8519 A wrapper for ocramius/package-versions to get pretty versions strings
league/csv                                8.x-dev d2aab1e    Csv data manipulation made easy in PHP
league/flysystem                          1.0.53             Filesystem abstraction: Many filesystems, one API.
littlegiant/silverstripe-config-validator 1.0                Build time configuration validation for SilverStripe framework.
m1/env                                    2.1.2              Env is a lightweight library bringing .env file parser compatibility to PHP. In short - it enables you to read .env files with PHP.
marcj/topsort                             1.1.0              High-Performance TopSort/Dependency resolving algorithm
monolog/monolog                           1.x-dev 17cbfb8    Sends your logs to files, sockets, inboxes, databases and various web services
nette/finder                              v2.5.x-dev 6be1b83 ? Nette Finder: find files and directories with an intuitive API.
nette/robot-loader                        dev-master a49e8e8 🍀 Nette RobotLoader: high performance and comfortable autoloader that will search and autoload classes within your application.
nette/utils                               dev-master 033486c 🛠 Nette Utils: lightweight utilities for string & array manipulation, image handling, safe JSON encoding/decoding, validation, slug or ...
nikic/php-parser                          3.x-dev bb87e28    A PHP parser written in PHP
ocramius/package-versions                 1.4.0              Composer plugin that provides efficient querying for installed package versions (no runtime IO)
padraic/humbug_get_contents               1.1.2              Secure wrapper for accessing HTTPS resources with file_get_contents for PHP 5.3+
padraic/phar-updater                      dev-master e5a5da3 A thing to make PHAR self-updating easy and secure.
paragonie/random_compat                   v2.0.18            PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
php-cs-fixer/diff                         v1.3.0             sebastian/diff v2 backport support for PHP5.6
phpspec/php-diff                          v1.1.0             A comprehensive library for generating differences between two hashable objects (strings or arrays).
phpstan/phpdoc-parser                     dev-master 8c4ef2a PHPDoc parser with support for nullable, intersection and generic types
phpstan/phpstan-php-parser                0.9                PHP-Parser extensions for PHPStan
phpstan/phpstan-shim                      0.9.2              PHPStan Phar distribution
psr/cache                                 dev-master 78c5a01 Common interface for caching libraries
psr/container                             1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                          dev-master f6561bf Common interface for HTTP messages
psr/log                                   dev-master c4421fc Common interface for logging libraries
psr/simple-cache                          dev-master 408d5ea Common interfaces for simple caching
ralouphie/getallheaders                   3.0.3              A polyfill for getallheaders.
silverstripe/assets                       1.x-dev 6425852    SilverStripe Assets component
silverstripe/config                       1.x-dev 772049f    SilverStripe configuration based on YAML and class statics
silverstripe/framework                    4.x-dev 844d2ef    The SilverStripe framework
silverstripe/upgrader                     dev-master bcbf2eb A tool to help upgrade your code to handle API changes in packages you used.
silverstripe/vendor-plugin                1.x-dev cf66429    Allows vendor modules to expose directories to the webroot
slevomat/coding-standard                  5.0.4              Slevomat Coding Standard for PHP_CodeSniffer complements Consistence Coding Standard by providing sniffs with additional checks.
squizlabs/php_codesniffer                 dev-master f6fd848 PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
sunnysideup/php_2_command_line            dev-master 652d156 Runs a bash script using PHP
swiftmailer/swiftmailer                   5.x-dev 181b89f    Swiftmailer, free feature-rich PHP mailer
symbiote/silverstripe-phpstan             dev-master 8fb6491 PHPStan for Silverstripe
symfony/cache                             3.4.x-dev 8c6e162  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                            3.4.x-dev dfa7b95  Symfony Config Component
symfony/console                           4.4.x-dev 59606f1  Symfony Console Component
symfony/debug                             4.3.x-dev 8ca4340  Symfony Debug Component
symfony/dependency-injection              3.4.x-dev 35e0525  Symfony DependencyInjection Component
symfony/event-dispatcher                  4.4.x-dev 030b51a  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts        dev-master c61766f Generic abstractions related to dispatching event
symfony/filesystem                        4.4.x-dev 4e3b24f  Symfony Filesystem Component
symfony/finder                            3.4.x-dev 1e762fd  Symfony Finder Component
symfony/http-foundation                   4.4.x-dev 732978b  Symfony HttpFoundation Component
symfony/http-kernel                       3.4.x-dev 56817d5  Symfony HttpKernel Component
symfony/mime                              4.4.x-dev de77c75  A library to manipulate MIME messages
symfony/options-resolver                  4.4.x-dev e8dccdc  Symfony OptionsResolver Component
symfony/polyfill-apcu                     dev-master a502fac Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype                    dev-master 82ebae0 Symfony polyfill for ctype functions
symfony/polyfill-intl-idn                 dev-master eff4216 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring                 dev-master fe5e94c Symfony polyfill for the Mbstring extension
symfony/polyfill-php70                    dev-master bc4858f Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72                    dev-master ab50dcf Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73                    dev-master 639cc79 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                           4.4.x-dev c89a858  Symfony Process Component
symfony/service-contracts                 dev-master f391a00 Generic abstractions related to writing services
symfony/stopwatch                         4.4.x-dev e6e6154  Symfony Stopwatch Component
symfony/translation                       2.8.x-dev fc58c2a  Symfony Translation Component
symfony/yaml                              3.4.x-dev 212a27b  Symfony Yaml Component
symplify/coding-standard                  dev-master 9ca4cb8 Set of Symplify rules for PHP_CodeSniffer and PHP CS Fixer.
symplify/easy-coding-standard             dev-master e2e004a Use Coding Standard with 0-knowledge of PHP-CS-Fixer and PHP_CodeSniffer.
symplify/package-builder                  dev-master 14db22e Dependency Injection, Console and Kernel toolkit for Symplify packages.

```

**Comment by sunnysideup** [comment]
this was some conflict with phpstan-shim ... ignore it.
