### ISSUE TITLE
upgrade nikic/php-parser to 4?

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-upgrader#186]
would it be possible to upgrade nikic/php-parser to version 4?  It may benefit this project and it would make it more compatible with other projects.

**Comment by dhensby** [comment]
I did just change the dependencies locally and it seemed to work fine. I don't think there are (m)any breaking changes, apart from the PHP version support

**Comment by PortableSteve** [comment]
@dhensby how did you achieve this? I can't update `nikic/php-parser` to v4 without also updating `phpstan/phpstan-php-parser` and `phpstan/phpstan` to at least v0.10.0 - which seems to contain api changes that break parts of the upgrader.

**Comment by PortableSteve** [comment]
For example, after upgrading the dependencies as above, then running `upgrade-code inspect ./mysite`:

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function PHPStan\DependencyInjection\ContainerFactory::create(), 2 passed in phar:///home/vagrant/upgrade-code-php73.phar/src/Util/PHPStanState.php on line 66 and exactly 3 expected in phar:///home/vagrant/upgrade-code-php73.phar/vendor/phpstan/phpstan/src/DependencyInjection/ContainerFactory.php:46
Stack trace:
#0 phar:///home/vagrant/upgrade-code-php73.phar/src/Util/PHPStanState.php(66): PHPStan\DependencyInjection\ContainerFactory->create('/tmp', Array)
#1 phar:///home/vagrant/upgrade-code-php73.phar/src/Util/PHPStanState.php(43): SilverStripe\Upgrader\Util\PHPStanState->initContainer()
#2 phar:///home/vagrant/upgrade-code-php73.phar/src/Console/InspectCommand.php(60): SilverStripe\Upgrader\Util\PHPStanState->init()
#3 phar:///home/vagrant/upgrade-code-php73.phar/vendor/symfony/console/Command/Command.php(255): SilverStripe\Upgrader\Console\InspectCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Con in phar:///home/vagrant/upgrade-code-php73.phar/vendor/phpstan/phpstan/src/DependencyInjection/ContainerFactory.php on line 46
```

**Comment by dhensby** [comment]
I think I upgraded both dependencies but I only had a very limited use case to test against and it wasn't one where phpstan was used.
