### ISSUE TITLE
Uncaught FilesystemException 

### ISSUE THREAD

**Issue by shannon-patterson** [silverstripe/silverstripe-upgrader#191]
Hi there,

I've been working on planning our Silverstripe upgrade for a couple of days now, and have been using the upgrade-code tool along the way.  I installed via the phar instructions on the upgrade guide. 

Today, after successfully using the tool to add namespaces to my project, I was ready to run the `upgrade` function, and got an error.  In fact, any time I do anything with `upgrade-code`, I get the following output

```
PHP Fatal error:  Uncaught Humbug\SelfUpdate\Exception\FilesystemException: The directory is not writeable: /usr/local/bin. in phar:///usr/local/bin/upgrade-code/vendor/padraic/phar-updater/src/Updater.php:462
Stack trace:
#0 phar:///usr/local/bin/upgrade-code/vendor/padraic/phar-updater/src/Updater.php(112): Humbug\SelfUpdate\Updater->setTempDirectory()
#1 phar:///usr/local/bin/upgrade-code/src/Util/UpdateChecker.php(37): Humbug\SelfUpdate\Updater->__construct('/usr/local/bin/...', false, 'github')
#2 phar:///usr/local/bin/upgrade-code/src/Util/UpdateChecker.php(61): SilverStripe\Upgrader\Util\UpdateChecker::getUpdater('1.4.3')
#3 phar:///usr/local/bin/upgrade-code/bin/upgrade-code(35): SilverStripe\Upgrader\Util\UpdateChecker::getShowNewVersion('1.4.3')
#4 /usr/local/bin/upgrade-code(5): require('phar:///usr/loc...')
#5 {main}
  thrown in phar:///usr/local/bin/upgrade-code/vendor/padraic/phar-updater/src/Updater.php on line 462
```

This happens with any number of arguments or flags, including `upgrade-code -v`

Any idea what might have happened?  The script hasn't moved, my php version hasn't changed (7.1.33), the permissions on /usr/local/bin are unlikely to have changed.

**Comment by maxime-rainville** [comment]
Looks like the self-update logic is trying to write something in its installation directory.

Maybe try running `sudo upgrade-code self-update` and see if it unblocks itself.

Ideally the self update logic should be smart enough to realised when the PHAR file is in a read-only location and prompt you to run the command as root.

**Comment by shannon-patterson** [comment]
I ended up making the directory writable in order to proceed, but am still puzzled as to why this happened after a day or two of not requiring the directory permission changes.  

Any idea what the phar was trying to write?  I can understand throwing this error if `self-update` had been called, but otherwise it doesn't make sense to me.

**Comment by maxime-rainville** [comment]
I haven't look at this in a while, but from memory I configured to upgrader to look up online to see if there's a newer version and display a message. To avoid always displaying the message, I write a temp file somewhere that should expire after a couple days. If the file is present and not-expired, the message is suppress.

It might be that file it's trying to write.

**Comment by OldStarchy** [comment]
Hello it looks like the problem is here

https://github.com/silverstripe/silverstripe-upgrader/blob/629316a2896a86919900acc022c513f84507d94b/src/Util/UpdateChecker.php#L37

Its setting the self-update directory to `\Phar::running(false)` but when running the update from the `composer global` install `\Phar::running` returns `''` when the current program is not a compiled phar ([docs](https://www.php.net/manual/en/phar.running.php)).

From what I can tell this causes `\Humbug\SelfUpdate\Updater` to try to write to `/` which is obviously not writable.
