### ISSUE TITLE
 PHP Fatal error while "Trying to curate dependencies by switching to recipes."

### ISSUE THREAD

**Issue by natschb** [silverstripe/silverstripe-upgrader#207]
I successfully used the upgrader several times, but now I get an error running:  
php upgrade-code.phar recompose --recipe-core-constraint="4.5" 

complete output:

Upgrading PHP constraint
========================

 Done.

Rebuilding dependencies
=======================

 ! [NOTE] Trying to re-require all packages                                                                             

 * Requiring php:">=7.4" .... ✔
 * Requiring silverstripe/recipe-core:"4.5.0" ............ ✔
 * Requiring silverstripe/recipe-cms:"*" ................... ✔
 * Requiring silverstripe/reports:"*" ............... ✗
 * Requiring silverstripe/siteconfig:"*" .............. ✗
 * Requiring undefinedoffset/sortablegridfield:"*" .............. ✗

 ! [NOTE] Trying to curate dependencies by switching to recipes.                                                        

[11-Jul-2023 23:53:28 Pacific/Auckland] PHP Fatal error:  Uncaught TypeError: Return value of SilverStripe\Upgrader\Composer\Package::getDevMaster() must be of the type array, null returned in phar:///var/www/html/upgrade-code.phar/src/Composer/Package.php:161
Stack trace:
#0 phar:///var/www/html/upgrade-code.phar/src/Composer/Package.php(268): SilverStripe\Upgrader\Composer\Package->getDevMaster()
#1 phar:///var/www/html/upgrade-code.phar/src/Composer/Recipe.php(69): SilverStripe\Upgrader\Composer\Package->getRequiredPackages()
#2 phar:///var/www/html/upgrade-code.phar/src/Composer/Recipe.php(84): SilverStripe\Upgrader\Composer\Recipe->buildDependencyTree(Array)
#3 phar:///var/www/html/upgrade-code.phar/src/Composer/Recipe.php(107): SilverStripe\Upgrader\Composer\Recipe->buildDependencyTree()
#4 phar:///var/www/html/upgrade-code.phar/src/Composer/Rules/Rebuild.php(415): SilverStripe\Upgrader\Composer\Recipe->subsetOf(Array)
#5 phar:///var/www/html/upgrade-code.phar/src/Composer/Rules/Rebuild.php(202): SilverStripe\Upgrader\Composer\Rules\Rebuild->findRecipeEquivale in phar:///var/www/html/upgrade-code.phar/src/Composer/Package.php on line 161

Fatal error: Uncaught TypeError: Return value of SilverStripe\Upgrader\Composer\Package::getDevMaster() must be of the type array, null returned in phar:///var/www/html/upgrade-code.phar/src/Composer/Package.php:161
Stack trace:
#0 phar:///var/www/html/upgrade-code.phar/src/Composer/Package.php(268): SilverStripe\Upgrader\Composer\Package->getDevMaster()
#1 phar:///var/www/html/upgrade-code.phar/src/Composer/Recipe.php(69): SilverStripe\Upgrader\Composer\Package->getRequiredPackages()
#2 phar:///var/www/html/upgrade-code.phar/src/Composer/Recipe.php(84): SilverStripe\Upgrader\Composer\Recipe->buildDependencyTree(Array)
#3 phar:///var/www/html/upgrade-code.phar/src/Composer/Recipe.php(107): SilverStripe\Upgrader\Composer\Recipe->buildDependencyTree()
#4 phar:///var/www/html/upgrade-code.phar/src/Composer/Rules/Rebuild.php(415): SilverStripe\Upgrader\Composer\Recipe->subsetOf(Array)
#5 phar:///var/www/html/upgrade-code.phar/src/Composer/Rules/Rebuild.php(202): SilverStripe\Upgrader\Composer\Rules\Rebuild->findRecipeEquivale in phar:///var/www/html/upgrade-code.phar/src/Composer/Package.php on line 161

**Comment by BoldNZ** [comment]
Any update on this?  I have the exact same issue trying to upgrade a site from Silverstripe 3.
I'm new to silverstripe and having great difficulty trying to manually upgrade.

**Comment by natschb** [comment]
> Any update on this? I have the exact same issue trying to upgrade a site from Silverstripe 3. I'm new to silverstripe and having great difficulty trying to manually upgrade.

Unfortunately no solution for this, I also do the updates manually ;(

**Comment by asecondwill** [comment]
same error.  at least this ticket saves me keep trying with the updater.
