### ISSUE TITLE
Inspect does not run

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-upgrader#70]
When I run the inspect command I get an error:

```
me@lappy:/var/www/upgradeto4$ php ~/.composer/vendor/bin/upgrade-code inspect ./my-module/ --write
Running post-upgrade on "/var/www/upgradeto4/my-module"
[2018-05-04 14:21:09] Applying ApiChangeWarningsRule to _config.php...
PHP Fatal error:  Uncaught TypeError: Argument 4 passed to PHPStan\Analyser\Scope::__construct() must be an instance of PHPStan\Analyser\ScopeContext, string given, called in /home/me/.composer/vendor/silverstripe/upgrader/src/UpgradeRule/PHP/Visitor/PHPStanScopeVisitor.php on line 64 and defined in /home/me/.composer/vendor/phpstan/phpstan/src/Analyser/Scope.php:136
Stack trace:
#0 /home/me/.composer/vendor/silverstripe/upgrader/src/UpgradeRule/PHP/Visitor/PHPStanScopeVisitor.php(64): PHPStan\Analyser\Scope->__construct(Object(PHPStan\Broker\Broker), Object(PhpParser\PrettyPrinter\Standard), Object(PHPStan\Analyser\TypeSpecifier), '/var/www/upgrad...')
#1 /home/me/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(80): SilverStripe\Upgrader\UpgradeRule\PHP\Visitor\PHPStanScopeVisitor->beforeTraverse(Array)
#2 /home/me/.composer/vendor/silverstripe/upgrader/src/UpgradeRule/PHP/PHPUpgradeRule.php(28): PhpParser\NodeTraverser->traverse(Array)
#3 /home/me/.composer/vendor/silverstripe/ in /home/me/.composer/vendor/phpstan/phpstan/src/Analyser/Scope.php on line 136
```

**Comment by robbieaverill** [comment]
Could you please provide your PHP version as well as a copy of your `composer show` output?

**Comment by sunnysideup** [comment]
composer show on project:

```txt
composer/ca-bundle                 1.1.1                   Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/installers                v1.5.0                  A multi-framework Composer library installer
doctrine/instantiator              1.1.0                   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
embed/embed                        v3.3.1                  PHP library to retrieve page info using oembed, opengraph, etc
guzzlehttp/psr7                    1.4.2                   PSR-7 message implementation that also provides common utility methods
intervention/image                 2.4.1                   Image handling and manipulation library with support for Laravel integration
league/flysystem                   1.0.44                  Filesystem abstraction: Many filesystems, one API.
m1/env                             2.1.0                   Env is a lightweight library bringing .env file parser compatibility to PHP. In short - it enables you to read .en...
marcj/topsort                      1.1.0                   High-Performance TopSort/Dependency resolving algorithm
monolog/monolog                    1.23.0                  Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                  1.7.0                   Create deep copies (clones) of your objects
nikic/php-parser                   v3.1.5                  A PHP parser written in PHP
paragonie/random_compat            v2.0.12                 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpdocumentor/reflection-common    1.0.1                   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.0                   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information...
phpdocumentor/type-resolver        0.4.0                  
phpspec/prophecy                   1.7.6                   Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          4.0.8                   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.5                   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1                   Simple template engine.
phpunit/php-timer                  1.0.9                   Utility class for timing
phpunit/php-token-stream           2.0.2                   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    5.7.27                  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       3.4.4                   Mock Object library for PHPUnit
psr/cache                          1.0.1                   Common interface for caching libraries
psr/container                      1.0.0                   Common Container Interface (PHP FIG PSR-11)
psr/http-message                   1.0.1                   Common interface for HTTP messages
psr/log                            1.0.2                   Common interface for logging libraries
psr/simple-cache                   1.0.1                   Common interfaces for simple caching
sebastian/code-unit-reverse-lookup 1.0.1                   Looks up which function or method a line of code belongs to
sebastian/comparator               1.2.4                   Provides the functionality to compare PHP values for equality
sebastian/diff                     1.4.3                   Diff implementation
sebastian/environment              2.0.0                   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 2.0.0                   Provides the functionality to export PHP variables for visualization
sebastian/global-state             1.1.1                   Snapshotting of global state
sebastian/object-enumerator        2.0.1                   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context        2.0.0                   Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0                   Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1                   Library that helps with managing the version number of Git-hosted PHP projects
silverstripe-themes/simple         dev-master 4d546a4      The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/admin                 1.1.0                   SilverStripe admin interface
silverstripe/asset-admin           1.1.0                   Asset management for the SilverStripe CMS
silverstripe/assets                1.1.0                   SilverStripe Assets component
silverstripe/campaign-admin        1.1.0                   SilverStripe campaign admin interface
silverstripe/cms                   4.1.0                   The SilverStripe Content Management System
silverstripe/config                1.0.4                   SilverStripe configuration based on YAML and class statics
silverstripe/errorpage             1.1.0                   ErrorPage component for SilverStripe CMS
silverstripe/framework             4.1.0                   The SilverStripe framework
silverstripe/graphql               1.1.0                   GraphQL server for SilverStripe models and other data
silverstripe/recipe-cms            1.1.0                   SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-core           1.1.0                   SilverStripe framework-only core recipe
silverstripe/recipe-plugin         1.2.0                   Helper plugin to install SilverStripe recipes
silverstripe/reports               4.1.0                   Reports module for SilverStripe CMS
silverstripe/siteconfig            4.1.0                   Site wide settings administration.
silverstripe/vendor-plugin         1.3.3                   Allows vendor modules to expose directories to the webroot
silverstripe/versioned             1.1.0                   SilverStripe Versioned component
sunnysideup/object-cacher          dev-4.1-upgrade 5db8d6f Cache data objects. Useful when you are working with large numbers and/or complex data objects that you need to ac...
swiftmailer/swiftmailer            v5.4.9                  Swiftmailer, free feature-rich PHP mailer
symfony/cache                      v3.4.9                  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                     v3.4.9                  Symfony Config Component
symfony/filesystem                 v4.0.9                  Symfony Filesystem Component
symfony/finder                     v3.4.9                  Symfony Finder Component
symfony/polyfill-apcu              v1.8.0                  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-mbstring          v1.8.0                  Symfony polyfill for the Mbstring extension
symfony/translation                v2.8.39                 Symfony Translation Component
symfony/yaml                       v3.4.9                  Symfony Yaml Component
webmozart/assert                   1.3.0                   Assertions to validate method input/output with nice error messages.
webonyx/graphql-php                v0.8.0                  A PHP port of GraphQL reference implementation
```

composer global show:
```txt
composer/xdebug-handler        1.1.0              Restarts a process without xdebug.
jean85/pretty-package-versions 1.1                A wrapper for ocramius/pretty-package-versions to get pretty versions strings
m1/env                         2.1.0              Env is a lightweight library bringing .env file parser compatibility to PHP. In short - it enables you to read .env files w...
nette/bootstrap                v2.4.5             🅱 Nette Bootstrap: the simple way to configure and bootstrap your Nette application.
nette/di                       v2.4.11            💎 Nette Dependency Injection Container: Flexible, compiled and full-featured DIC with perfectly usable autowiring and su...
nette/finder                   v2.4.1             Nette Finder: Files Searching
nette/neon                     v2.4.2             Nette NEON: parser & generator for Nette Object Notation
nette/php-generator            v3.0.4             🐘 Nette PHP Generator: generates neat PHP code for you. Supports new PHP 7.2 features.
nette/robot-loader             v3.0.3             🍀 Nette RobotLoader: high performance and comfortable autoloader that will search and autoload classes within your appli...
nette/utils                    v2.5.1             🛠 Nette Utils: lightweight utilities for string & array manipulation, image handling, safe JSON encoding/decoding, valid...
nikic/php-parser               v3.1.5             A PHP parser written in PHP
ocramius/package-versions      1.3.0              Composer plugin that provides efficient querying for installed package versions (no runtime IO)
phpspec/php-diff               v1.1.0             A comprehensive library for generating differences between two hashable objects (strings or arrays).
phpstan/phpdoc-parser          dev-master aa22c2f PHPDoc parser with support for nullable, intersection and generic types
phpstan/phpstan                dev-master b57767c PHPStan - PHP Static Analysis Tool
phpstan/phpstan-php-parser     dev-master 45cc47c PHP-Parser extensions for PHPStan
psr/log                        1.0.2              Common interface for logging libraries
silverstripe/upgrader          dev-master 73a6348 A tool to help upgrade your code to handle API changes in packages you used.
symfony/console                v3.4.9             Symfony Console Component
symfony/debug                  v4.0.9             Symfony Debug Component
symfony/finder                 v4.0.9             Symfony Finder Component
symfony/polyfill-mbstring      v1.8.0             Symfony polyfill for the Mbstring extension
symfony/yaml                   v3.4.9             Symfony Yaml Component

```
php -v:

``` txt
PHP 7.1.16-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:47:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.16-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by maxime-rainville** [comment]
The problem is that we are requiring a dev version of phpstan and phpstan-php-parser. There's no stable 0.10 release for either of those so it installs a dev version instead.

It doesn't hurt us most of the time because our composer.lock file fixes the versions we use to one that is compatible with our API calls.

I'll try changing the constraint on both of those packages to be ^0.9.0. This should install the stable release.

**Comment by unclecheese** [comment]
The https://github.com/silverstripe/silverstripe-upgrader/pull/80 merge closes this.
